graph TD;
    A[S3 Bucket] -->|S3 Event Notification| B[Lambda Function];
    B -->|Process JSON| C[AWS Well-Architected Tool];
    B -->|Download JSON| A;
    B -.->|Assume Role| D[IAM Role];
    D --> B;
    X[User] --> |File Upload| A[S3 Bucket];
    C -->|Create Workload| E[Workload];
    C -->|Apply Lens| F[Lens Review];
    C -->|Answer Questions| G[Question Answers];
    C -->|Generate Report| H[Report PDF in S3];
    H -->|Uploaded Report| A;
    H -->|Send Notification| I[SNS Topic];